easy_admin:
    entities:
        Commande:
          class: App\Entity\Commande
          list:
            fields:
              - {property: "fonction"}
        Commande2:
          class: App\Entity\CommandeCoating
        Fonction:
          class: App\Entity\Fonction